### ISSUE TITLE
Live Demo for "REACTing Codepen Comment Editor" does not work

### ISSUE THREAD

**Issue by brettimus** [nikgraf/awesome-draft-js#70]
Seems like the codepen demo under "REACTing Codepen Comment Editor - Draft.js" isn't working anymore? 

https://codepen.io/rkpasia/full/jqbrpq

**Comment by nikgraf** [comment]
thx @brettimus 👏

**Comment by ddelrio1986** [comment]
It does work. You just land on the full view in codepen. Just switch the view if you want to see the code or anything else.

**Comment by brettimus** [comment]
yeah so it's not interactive for me? i.e., I can't actually experiment with keyboard shortcuts or tagging, which seems to be the point of the example (to interact with a live editor instance)

looked at it in chrome and safari, both latest version
